### ISSUE TITLE
NFS plugin instructions do not match NFS command path in nfs.py

### ISSUE THREAD

**Issue by exp-hc** [site24x7/plugins#19]
Per instructions in nfs_readme, the following line should be updated.            

Current: 
NFS_COMMAND = ["/opt/site24x7/monagent/plugins/nfs_check.sh",mounts] 
Update:
NFS_COMMAND = ["/opt/site24x7/monagent/plugins/nfs/nfs_check.sh",mounts]

**Comment by site24x7** [comment]
Hi @exp-hc ,

Thanks for pointing out the issue.. it has been fixed and updated.
