### ISSUE TITLE
Error: apache instance has no attribute '_realm'

### ISSUE THREAD

**Issue by sanbotto** [site24x7/plugins#20]
Hi! I'm having the same issue with 3 different Linux servers (CloudLinux 7.8, CentOS 7.7.1908 and CentOS 7.8.2003) when trying to use this script to monitor Apache. Site24x7 console shows me the following at Plugin Integrations:

> Exception occured in collecting data : apache instance has no attribute '_realm'

Is there a missing declaration needed to use **self._realm** at lines **64** and **92** of apache.py or am I missing an Apache module on all my servers?

Thanks!

**Comment by site24x7** [comment]
Hi Sanbotto,

The issue has been fixed and updated.
