### ISSUE TITLE
error testing connections 

### ISSUE THREAD

**Issue by sap-all-chile** [site24x7/plugins#204]
when testing the connection it raises this error

xxxxxxxx:/opt/site24x7/monagent/plugins/sap_hana_database # python sap_hana_database.py --host=saperpdevdb --port=30015 --username=site24x7 --password=xxxxxx Traceback (most recent call last):
  File "sap_hana_database.py", line 3, in <module>
    from hdbcli import dbapi
ImportError: No module named hdbcli

hdbcli was successfully installed in step 1, it seems to be a environment variable misssing

**Comment by Sathvika-a** [comment]
hdbcli driver supports for python 2.7, python 3.4 and above. Please check if any of the hdbcli driver supported python version is available. If so, run the plugin with below command.
python<version> sap_hana_database.py --host=saperpdevdb --port=30015 --username=site24x7 --password=xxxxxx.

**Comment by MuraliKrishnanSite24x7** [comment]
Since we replied to your query to use with appropriate Python version. We are closing this case.
