### ISSUE TITLE
/plugins/master/sendgrid/sendgrid.py variable assignment error

### ISSUE THREAD

**Issue by zpbonjour** [site24x7/plugins#340]
on line 58, the variable assignment is backwards.  As it currently is, API_KEY is always being assigned as a NoneType.

It should be 
`args.api_key=API_KEY`

**Comment by MuraliKrishnanSite24x7** [comment]
Thanks for the comment.

We changed the SendGrid.py script to read the configuration from Sendgrid.cfg file. In the cfg file, the user can configure the API_KEY, it will be read by SendGrid.py and perform Data collection.

**Comment by zpbonjour** [comment]
@MuraliKrishnanSite24x7 When did that change?  I am only talking about the current version of the plugin currently available to use.  These issues remain, so why did you close this?

If a cfg file is supposed to be used, then these issues are still present:
1. The documentation does not mention anything about the cfg file.  Both the readme and the public docs page.
2. Nowhere in the sendgrid.py file is a cfg file being read or referenced.
3. On line 19, "API_KEY" is still being assigned and there is a placeholder value that is expected to be replaced with the actual Sendgrid API key.  

My original issue is still outstanding.  On line 58, API_KEY is being reassigned as a NoneType and thus discarding the value 
that was assigned on line 19.

`API_KEY=args.api_key`

This needs to be reversed so the parser args element "api_key" is assigned the value of API_KEY, and not the other way around.
