### ISSUE TITLE
Unable to run php agent on PHP7

### ISSUE THREAD

**Issue by chiukicom** [site24x7/plugins#4]
PHP agent crashing the web server and making our API unavailable.

when the zpa.ini file is added, the web server (apache2 on centos 7 with php7) immediately crashes.
[root@beta php.d]# php -a
Interactive shell

Segmentation fault
[root@beta php.d]# cat zpa.ini
[zpa]
extension="/usr/local/lib/zpa/zpa.so"
[root@beta php.d]# ldd /usr/local/lib/zpa/zpa.so
ldd: warning: you do not have execution permission for `/usr/local/lib/zpa/zpa.so'
        linux-vdso.so.1 =>  (0x00007ffe2d7da000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb9a5ca0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb9a6271000)
[root@beta php.d]# ll /usr/local/lib/zpa/zpa.so
-rw-rw-r-- 1 idan idan 128216 Dec  7 10:37 /usr/local/lib/zpa/zpa.so
[root@beta php.d]# chmod +x /usr/local/lib/zpa/zpa.so
[root@beta php.d]# ldd /usr/local/lib/zpa/zpa.so
        linux-vdso.so.1 =>  (0x00007ffc4f72b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa632157000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa632728000)
[root@beta php.d]# php
Segmentation fault
[root@beta php.d]# vi /etc/php.d/zpa.ini

**Comment by teejayen** [comment]
We are having this issue with the latest update to the Site24x7 agent. Have logged a support case, and am waiting a response.

Have temporarily commented out zpa.so from the ini file.

`php-fpm-5.6[658]: segfault at 53 ip 00007f54ceae2881 sp 00007fffe52e2ac0 error 4 in zpa.so[7f54ceadf000+6000]`

**Comment by site24x7** [comment]
Hi,


Thanks for contacting Site24x7 support.


We are analyzing the case and will get back to you with an update shortly.



Regards

Joshua Ambrose

Site24x7 Team | ZOHO Corp

Phone: +1 408 352 9117 | +44 203 564 7893

4141 Hacienda Dr, Pleasanton, CA 94588, USA

About - Site24x7  | Help Guide | Knowledge Base | Community | Demo | Training

If you have any concerns please mail to escalations@site24x7.com

ISO/IEC 27001 & SOC 2 Certified

**Comment by site24x7** [comment]
Hi,

We request you to zip the logs from the /zpa/logs directory and upload it to us using the below link:
https://bonitas2.zohocorp.com/#to=support@site24x7.com&ticketid= 549225 


Also, we request you to share the backtrace regarding the error that you are facing with our agent. 


We look forward to hear from you. 


Regards,

Muralee S

Site24x7 Team | ZOHO Corp

US: +1 408 352 9117|UK: +44 203 564 7893
4141 Hacienda Dr, Pleasanton, CA 94588, USA
About Us  | Help Guide | Knowledge Base | Community | Webinars | Demo | Training

If you have any concerns please mail to escalations@site24x7.com

ISO/IEC 27001 & SOC 2 Certified

**Comment by teejayen** [comment]
Muralee, I logged a direct support case for this issue who recommended I update the agent and this seems to have resolved the issue.

**Comment by site24x7** [comment]
Hi,



Thank you for the update. 



Please write to us at support@site24x7.com for any clarifications or assistance required with Site24x7 and we will be more than happy to assist further. 



Regards,

Muralee S

Site24x7 Team | ZOHO Corp

US: +1 408 352 9117|UK: +44 203 564 7893
4141 Hacienda Dr, Pleasanton, CA 94588, USA
About Us  | Help Guide | Knowledge Base | Community | Webinars | Demo | Training

If you have any concerns please mail to escalations@site24x7.com

ISO/IEC 27001 & SOC 2 Certified
