### ISSUE TITLE
NGINX Plus does not support status page

### ISSUE THREAD

**Issue by centennialwebmaster** [site24x7/plugins#51]
NGINX Plus no longer supports the /status page and now uses the /api URL for getting stats so the nginxplus.py plugin no longer works

Any chance of getting an updated version of the nginxplus.py to support the new /api URL.  

See https://www.nginx.com/blog/transitioning-to-nginx-plus-api-configuration-monitoring/ for info.

**Comment by MuraliKrishnanSite24x7** [comment]
Thanks for the issue. 

We fixed the NGINX plus plugin with URL API. Please check and update us in case of any requirements. 

https://github.com/site24x7/plugins/tree/master/nginxplus
