### ISSUE TITLE
File Size Plugin for Linux reporting the wrong file size unit

### ISSUE THREAD

**Issue by gabricar** [site24x7/plugins#83]
File size reports the file in KB but the collected value is Byte. Site24x7 UI reports my 2GB file in TB

File on the server:
in K
du -sk /opt/etcd/ef2f/data/member/snap/db
2105544	/opt/etcd/ef2f/data/member/snap/db

in G
du -sh /opt/etcd/ef2f/data/member/snap/db
2.1G	/opt/etcd/ef2f/data/member/snap/db

in B
du -sb /opt/etcd/ef2f/data/member/snap/db
**2156027904**	/opt/etcd/ef2f/data/member/snap/db

collected metrics:
 python file_monitoring.py --filename="/opt/etcd/ef2f/data/member/snap/db" --case_sensitive="True"
{
    "time_since_last_accessed": 13749, 
    "plugin_version": 1, 
    "last_access_time": "Thu May 14 14:40:11 2020", 
    "file_owner_id": 1001, 
    "last_modified_time": "Wed Dec  8 11:33:28 2021", 
    "time_since_last_modified": 0, 
    "content_match": "no Search Key", 
    "file_index": 100731885, 
    "hash_value_changed": 1, 
    "file_size": **2156027904**, 
    "units": {
        "time_since_last_modified": "hours", 
        "time_since_last_accessed": "hours", 
        "file_size": "kb"
    }, 
    "heartbeat_required": true, 
    "read_access": 1, 
    "execution_access": 1, 
    "write_access": 1, 
    "content_occurance_count": 0
}

site 24x7 UI:
![image](https://user-images.githubusercontent.com/24420279/145250655-6b528953-1e00-4f19-8e9a-68f086129a4a.png)

**Comment by MuraliKrishnanSite24x7** [comment]
Thanks for reporting the issue. We will analyze the case and get back.

**Comment by MuraliKrishnanSite24x7** [comment]
We fixed the issue. Hence closing the issue.
