### ISSUE TITLE
[mysq] Add option to use MySQL user config

### ISSUE THREAD

**Issue by rodehoed** [site24x7/plugins#9]
Hi,

Could you add an option to use 'read_default_file'? This makes it easy to let the authentication handled by my.cnf instead the credentials in this plugin.

Info is located: http://pymysql.readthedocs.io/en/latest/modules/connections.html . 

**Example:** 
`db = pymysql.connect(host=self.host, user=self.username, passwd=self.password, port=int(self.port), unix_socket=_output, read_default_file="/root/.my.cnf")`

**Comment by site24x7** [comment]
Hi, 

Thanks for contacting Site24x7. 

We acknowledged the issue already in site24x7 [community ](https://www.site24x7.com/community/mysql) and hope that helped. Please revert for any further clarification.
